baseURL = "http://s33h0w.me"
title = "s33h0w.me"
theme = "hechang"

[params]
  author = "s33h0w"
  description = "Personal blog, be indie"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "posts"
    url = "/posts/"
