baseURL = "http://s33h0w.me"
languageCode = "en-us"
title = "s33h0w.me"
theme = "hechang"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "posts"
    url = "/posts/"
